(cl:defpackage multi_mav_manager-srv
  (:use )
  (:export
   "FORMATION"
   "<FORMATION-REQUEST>"
   "FORMATION-REQUEST"
   "<FORMATION-RESPONSE>"
   "FORMATION-RESPONSE"
   "RAWPOSFORMATION"
   "<RAWPOSFORMATION-REQUEST>"
   "RAWPOSFORMATION-REQUEST"
   "<RAWPOSFORMATION-RESPONSE>"
   "RAWPOSFORMATION-RESPONSE"
  ))

