// Generated by gencpp from file multi_mav_manager/RawPosFormationRequest.msg
// DO NOT EDIT!


#ifndef MULTI_MAV_MANAGER_MESSAGE_RAWPOSFORMATIONREQUEST_H
#define MULTI_MAV_MANAGER_MESSAGE_RAWPOSFORMATIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <quadrotor_msgs/FlatOutputs.h>

namespace multi_mav_manager
{
template <class ContainerAllocator>
struct RawPosFormationRequest_
{
  typedef RawPosFormationRequest_<ContainerAllocator> Type;

  RawPosFormationRequest_()
    : goals()  {
    }
  RawPosFormationRequest_(const ContainerAllocator& _alloc)
    : goals(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::quadrotor_msgs::FlatOutputs_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::quadrotor_msgs::FlatOutputs_<ContainerAllocator> >::other >  _goals_type;
  _goals_type goals;




  typedef boost::shared_ptr< ::multi_mav_manager::RawPosFormationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::multi_mav_manager::RawPosFormationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RawPosFormationRequest_

typedef ::multi_mav_manager::RawPosFormationRequest_<std::allocator<void> > RawPosFormationRequest;

typedef boost::shared_ptr< ::multi_mav_manager::RawPosFormationRequest > RawPosFormationRequestPtr;
typedef boost::shared_ptr< ::multi_mav_manager::RawPosFormationRequest const> RawPosFormationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::multi_mav_manager::RawPosFormationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::multi_mav_manager::RawPosFormationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace multi_mav_manager

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'quadrotor_msgs': ['/home/aarow/ros/vio_swarm_groundstation_ws/src/quadrotor_control/quadrotor_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::multi_mav_manager::RawPosFormationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::multi_mav_manager::RawPosFormationRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multi_mav_manager::RawPosFormationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::multi_mav_manager::RawPosFormationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_mav_manager::RawPosFormationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::multi_mav_manager::RawPosFormationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::multi_mav_manager::RawPosFormationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e8201c3a37dceb4a570363e2bc87d7de";
  }

  static const char* value(const ::multi_mav_manager::RawPosFormationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe8201c3a37dceb4aULL;
  static const uint64_t static_value2 = 0x570363e2bc87d7deULL;
};

template<class ContainerAllocator>
struct DataType< ::multi_mav_manager::RawPosFormationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "multi_mav_manager/RawPosFormationRequest";
  }

  static const char* value(const ::multi_mav_manager::RawPosFormationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::multi_mav_manager::RawPosFormationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "quadrotor_msgs/FlatOutputs[] goals\n\
\n\
================================================================================\n\
MSG: quadrotor_msgs/FlatOutputs\n\
float32 x\n\
float32 y\n\
float32 z\n\
float32 yaw\n\
";
  }

  static const char* value(const ::multi_mav_manager::RawPosFormationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::multi_mav_manager::RawPosFormationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.goals);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RawPosFormationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::multi_mav_manager::RawPosFormationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::multi_mav_manager::RawPosFormationRequest_<ContainerAllocator>& v)
  {
    s << indent << "goals[]" << std::endl;
    for (size_t i = 0; i < v.goals.size(); ++i)
    {
      s << indent << "  goals[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::quadrotor_msgs::FlatOutputs_<ContainerAllocator> >::stream(s, indent + "    ", v.goals[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MULTI_MAV_MANAGER_MESSAGE_RAWPOSFORMATIONREQUEST_H
