// Generated by gencpp from file multi_mav_manager/RawPosFormation.msg
// DO NOT EDIT!


#ifndef MULTI_MAV_MANAGER_MESSAGE_RAWPOSFORMATION_H
#define MULTI_MAV_MANAGER_MESSAGE_RAWPOSFORMATION_H

#include <ros/service_traits.h>


#include <multi_mav_manager/RawPosFormationRequest.h>
#include <multi_mav_manager/RawPosFormationResponse.h>


namespace multi_mav_manager
{

struct RawPosFormation
{

typedef RawPosFormationRequest Request;
typedef RawPosFormationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RawPosFormation
} // namespace multi_mav_manager


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::multi_mav_manager::RawPosFormation > {
  static const char* value()
  {
    return "4fedc5f0f5ef4fa43b290be6cfe0b1a7";
  }

  static const char* value(const ::multi_mav_manager::RawPosFormation&) { return value(); }
};

template<>
struct DataType< ::multi_mav_manager::RawPosFormation > {
  static const char* value()
  {
    return "multi_mav_manager/RawPosFormation";
  }

  static const char* value(const ::multi_mav_manager::RawPosFormation&) { return value(); }
};


// service_traits::MD5Sum< ::multi_mav_manager::RawPosFormationRequest> should match 
// service_traits::MD5Sum< ::multi_mav_manager::RawPosFormation > 
template<>
struct MD5Sum< ::multi_mav_manager::RawPosFormationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::multi_mav_manager::RawPosFormation >::value();
  }
  static const char* value(const ::multi_mav_manager::RawPosFormationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::multi_mav_manager::RawPosFormationRequest> should match 
// service_traits::DataType< ::multi_mav_manager::RawPosFormation > 
template<>
struct DataType< ::multi_mav_manager::RawPosFormationRequest>
{
  static const char* value()
  {
    return DataType< ::multi_mav_manager::RawPosFormation >::value();
  }
  static const char* value(const ::multi_mav_manager::RawPosFormationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::multi_mav_manager::RawPosFormationResponse> should match 
// service_traits::MD5Sum< ::multi_mav_manager::RawPosFormation > 
template<>
struct MD5Sum< ::multi_mav_manager::RawPosFormationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::multi_mav_manager::RawPosFormation >::value();
  }
  static const char* value(const ::multi_mav_manager::RawPosFormationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::multi_mav_manager::RawPosFormationResponse> should match 
// service_traits::DataType< ::multi_mav_manager::RawPosFormation > 
template<>
struct DataType< ::multi_mav_manager::RawPosFormationResponse>
{
  static const char* value()
  {
    return DataType< ::multi_mav_manager::RawPosFormation >::value();
  }
  static const char* value(const ::multi_mav_manager::RawPosFormationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MULTI_MAV_MANAGER_MESSAGE_RAWPOSFORMATION_H
