// Generated by gencpp from file mav_manager/GoalTimed.msg
// DO NOT EDIT!


#ifndef MAV_MANAGER_MESSAGE_GOALTIMED_H
#define MAV_MANAGER_MESSAGE_GOALTIMED_H

#include <ros/service_traits.h>


#include <mav_manager/GoalTimedRequest.h>
#include <mav_manager/GoalTimedResponse.h>


namespace mav_manager
{

struct GoalTimed
{

typedef GoalTimedRequest Request;
typedef GoalTimedResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GoalTimed
} // namespace mav_manager


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mav_manager::GoalTimed > {
  static const char* value()
  {
    return "3200a97d30222d1d03961acacb87f306";
  }

  static const char* value(const ::mav_manager::GoalTimed&) { return value(); }
};

template<>
struct DataType< ::mav_manager::GoalTimed > {
  static const char* value()
  {
    return "mav_manager/GoalTimed";
  }

  static const char* value(const ::mav_manager::GoalTimed&) { return value(); }
};


// service_traits::MD5Sum< ::mav_manager::GoalTimedRequest> should match 
// service_traits::MD5Sum< ::mav_manager::GoalTimed > 
template<>
struct MD5Sum< ::mav_manager::GoalTimedRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mav_manager::GoalTimed >::value();
  }
  static const char* value(const ::mav_manager::GoalTimedRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mav_manager::GoalTimedRequest> should match 
// service_traits::DataType< ::mav_manager::GoalTimed > 
template<>
struct DataType< ::mav_manager::GoalTimedRequest>
{
  static const char* value()
  {
    return DataType< ::mav_manager::GoalTimed >::value();
  }
  static const char* value(const ::mav_manager::GoalTimedRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mav_manager::GoalTimedResponse> should match 
// service_traits::MD5Sum< ::mav_manager::GoalTimed > 
template<>
struct MD5Sum< ::mav_manager::GoalTimedResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mav_manager::GoalTimed >::value();
  }
  static const char* value(const ::mav_manager::GoalTimedResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mav_manager::GoalTimedResponse> should match 
// service_traits::DataType< ::mav_manager::GoalTimed > 
template<>
struct DataType< ::mav_manager::GoalTimedResponse>
{
  static const char* value()
  {
    return DataType< ::mav_manager::GoalTimed >::value();
  }
  static const char* value(const ::mav_manager::GoalTimedResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MAV_MANAGER_MESSAGE_GOALTIMED_H
