// Generated by gencpp from file multi_mav_manager/Formation.msg
// DO NOT EDIT!


#ifndef MULTI_MAV_MANAGER_MESSAGE_FORMATION_H
#define MULTI_MAV_MANAGER_MESSAGE_FORMATION_H

#include <ros/service_traits.h>


#include <multi_mav_manager/FormationRequest.h>
#include <multi_mav_manager/FormationResponse.h>


namespace multi_mav_manager
{

struct Formation
{

typedef FormationRequest Request;
typedef FormationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Formation
} // namespace multi_mav_manager


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::multi_mav_manager::Formation > {
  static const char* value()
  {
    return "906f4ece79b3c9d0d3067fa07f7fd334";
  }

  static const char* value(const ::multi_mav_manager::Formation&) { return value(); }
};

template<>
struct DataType< ::multi_mav_manager::Formation > {
  static const char* value()
  {
    return "multi_mav_manager/Formation";
  }

  static const char* value(const ::multi_mav_manager::Formation&) { return value(); }
};


// service_traits::MD5Sum< ::multi_mav_manager::FormationRequest> should match 
// service_traits::MD5Sum< ::multi_mav_manager::Formation > 
template<>
struct MD5Sum< ::multi_mav_manager::FormationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::multi_mav_manager::Formation >::value();
  }
  static const char* value(const ::multi_mav_manager::FormationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::multi_mav_manager::FormationRequest> should match 
// service_traits::DataType< ::multi_mav_manager::Formation > 
template<>
struct DataType< ::multi_mav_manager::FormationRequest>
{
  static const char* value()
  {
    return DataType< ::multi_mav_manager::Formation >::value();
  }
  static const char* value(const ::multi_mav_manager::FormationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::multi_mav_manager::FormationResponse> should match 
// service_traits::MD5Sum< ::multi_mav_manager::Formation > 
template<>
struct MD5Sum< ::multi_mav_manager::FormationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::multi_mav_manager::Formation >::value();
  }
  static const char* value(const ::multi_mav_manager::FormationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::multi_mav_manager::FormationResponse> should match 
// service_traits::DataType< ::multi_mav_manager::Formation > 
template<>
struct DataType< ::multi_mav_manager::FormationResponse>
{
  static const char* value()
  {
    return DataType< ::multi_mav_manager::Formation >::value();
  }
  static const char* value(const ::multi_mav_manager::FormationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MULTI_MAV_MANAGER_MESSAGE_FORMATION_H
