// Generated by gencpp from file trackers_manager/TransitionResponse.msg
// DO NOT EDIT!


#ifndef TRACKERS_MANAGER_MESSAGE_TRANSITIONRESPONSE_H
#define TRACKERS_MANAGER_MESSAGE_TRANSITIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace trackers_manager
{
template <class ContainerAllocator>
struct TransitionResponse_
{
  typedef TransitionResponse_<ContainerAllocator> Type;

  TransitionResponse_()
    {
    }
  TransitionResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::trackers_manager::TransitionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::trackers_manager::TransitionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TransitionResponse_

typedef ::trackers_manager::TransitionResponse_<std::allocator<void> > TransitionResponse;

typedef boost::shared_ptr< ::trackers_manager::TransitionResponse > TransitionResponsePtr;
typedef boost::shared_ptr< ::trackers_manager::TransitionResponse const> TransitionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::trackers_manager::TransitionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::trackers_manager::TransitionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace trackers_manager

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::trackers_manager::TransitionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::trackers_manager::TransitionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::trackers_manager::TransitionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::trackers_manager::TransitionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::trackers_manager::TransitionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::trackers_manager::TransitionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::trackers_manager::TransitionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::trackers_manager::TransitionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::trackers_manager::TransitionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "trackers_manager/TransitionResponse";
  }

  static const char* value(const ::trackers_manager::TransitionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::trackers_manager::TransitionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
";
  }

  static const char* value(const ::trackers_manager::TransitionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::trackers_manager::TransitionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TransitionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::trackers_manager::TransitionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::trackers_manager::TransitionResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // TRACKERS_MANAGER_MESSAGE_TRANSITIONRESPONSE_H
