// Generated by gencpp from file trackers_manager/TransitionRequest.msg
// DO NOT EDIT!


#ifndef TRACKERS_MANAGER_MESSAGE_TRANSITIONREQUEST_H
#define TRACKERS_MANAGER_MESSAGE_TRANSITIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace trackers_manager
{
template <class ContainerAllocator>
struct TransitionRequest_
{
  typedef TransitionRequest_<ContainerAllocator> Type;

  TransitionRequest_()
    : tracker()  {
    }
  TransitionRequest_(const ContainerAllocator& _alloc)
    : tracker(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _tracker_type;
  _tracker_type tracker;




  typedef boost::shared_ptr< ::trackers_manager::TransitionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::trackers_manager::TransitionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct TransitionRequest_

typedef ::trackers_manager::TransitionRequest_<std::allocator<void> > TransitionRequest;

typedef boost::shared_ptr< ::trackers_manager::TransitionRequest > TransitionRequestPtr;
typedef boost::shared_ptr< ::trackers_manager::TransitionRequest const> TransitionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::trackers_manager::TransitionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::trackers_manager::TransitionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace trackers_manager

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::trackers_manager::TransitionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::trackers_manager::TransitionRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::trackers_manager::TransitionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::trackers_manager::TransitionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::trackers_manager::TransitionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::trackers_manager::TransitionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::trackers_manager::TransitionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3ed2ea9cfbf7aece5bb9c39adf1f02b7";
  }

  static const char* value(const ::trackers_manager::TransitionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3ed2ea9cfbf7aeceULL;
  static const uint64_t static_value2 = 0x5bb9c39adf1f02b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::trackers_manager::TransitionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "trackers_manager/TransitionRequest";
  }

  static const char* value(const ::trackers_manager::TransitionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::trackers_manager::TransitionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string tracker\n\
";
  }

  static const char* value(const ::trackers_manager::TransitionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::trackers_manager::TransitionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.tracker);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TransitionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::trackers_manager::TransitionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::trackers_manager::TransitionRequest_<ContainerAllocator>& v)
  {
    s << indent << "tracker: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.tracker);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TRACKERS_MANAGER_MESSAGE_TRANSITIONREQUEST_H
